# Generated by Django 2.2 on 2020-02-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApplication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
